[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbyIqsKRANwDwWkZ4e9BzTfFJvstLBmhVw_doFExzf2deS1WycK36F9bj2F7urkSLanivA/exec"
  status = 200
  force = true

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



